--EQ_TYPE_TOTAL--

--TYPE_EQ_NUM		裝備種類總數編號	
--TYPE_EQ_QTY		裝備種類數量	
--TYPE_EQ_NAME		裝備種類總數名稱	

--ET00000001 帳篷
--ET00000002 頭燈


INSERT INTO EQ_TYPE_TOTAL(TYPE_EQ_NUM,TYPE_EQ_QTY,TYPE_EQ_NAME)
VALUES ('ET'||LPAD(to_char(SEQ_TYPE_TOTAL.nextval), 8, '0'),20,'帳篷');

INSERT INTO EQ_TYPE_TOTAL(TYPE_EQ_NUM,TYPE_EQ_QTY,TYPE_EQ_NAME)
VALUES ('ET'||LPAD(to_char(SEQ_TYPE_TOTAL.nextval), 8, '0'),20,'帳篷');

INSERT INTO EQ_TYPE_TOTAL(TYPE_EQ_NUM,TYPE_EQ_QTY,TYPE_EQ_NAME)
VALUES ('ET'||LPAD(to_char(SEQ_TYPE_TOTAL.nextval), 8, '0'),20,'登山杖');

INSERT INTO EQ_TYPE_TOTAL(TYPE_EQ_NUM,TYPE_EQ_QTY,TYPE_EQ_NAME)
VALUES ('ET'||LPAD(to_char(SEQ_TYPE_TOTAL.nextval), 8, '0'),20,'登山杖');

INSERT INTO EQ_TYPE_TOTAL(TYPE_EQ_NUM,TYPE_EQ_QTY,TYPE_EQ_NAME)
VALUES ('ET'||LPAD(to_char(SEQ_TYPE_TOTAL.nextval), 8, '0'),20,'照明燈');

INSERT INTO EQ_TYPE_TOTAL(TYPE_EQ_NUM,TYPE_EQ_QTY,TYPE_EQ_NAME)
VALUES ('ET'||LPAD(to_char(SEQ_TYPE_TOTAL.nextval), 8, '0'),20,'照明燈');

INSERT INTO EQ_TYPE_TOTAL(TYPE_EQ_NUM,TYPE_EQ_QTY,TYPE_EQ_NAME)
VALUES ('ET'||LPAD(to_char(SEQ_TYPE_TOTAL.nextval), 8, '0'),20,'照明燈');

INSERT INTO EQ_TYPE_TOTAL(TYPE_EQ_NUM,TYPE_EQ_QTY,TYPE_EQ_NAME)
VALUES ('ET'||LPAD(to_char(SEQ_TYPE_TOTAL.nextval), 8, '0'),20,'冰斧');

INSERT INTO EQ_TYPE_TOTAL(TYPE_EQ_NUM,TYPE_EQ_QTY,TYPE_EQ_NAME)
VALUES ('ET'||LPAD(to_char(SEQ_TYPE_TOTAL.nextval), 8, '0'),20,'安全帽');

INSERT INTO EQ_TYPE_TOTAL(TYPE_EQ_NUM,TYPE_EQ_QTY,TYPE_EQ_NAME)
VALUES ('ET'||LPAD(to_char(SEQ_TYPE_TOTAL.nextval), 8, '0'),20,'繩線');

INSERT INTO EQ_TYPE_TOTAL(TYPE_EQ_NUM,TYPE_EQ_QTY,TYPE_EQ_NAME)
VALUES ('ET'||LPAD(to_char(SEQ_TYPE_TOTAL.nextval), 8, '0'),20,'吊帶');

INSERT INTO EQ_TYPE_TOTAL(TYPE_EQ_NUM,TYPE_EQ_QTY,TYPE_EQ_NAME)
VALUES ('ET'||LPAD(to_char(SEQ_TYPE_TOTAL.nextval), 8, '0'),20,'冰爪');