--EQUIPMENT Data--
--對應TABLE EQUIPMENT
--1.EQ_NUM			裝備編號	
--2.EQ_NAME			裝備名稱	
--3.EQ_TYPE			裝備類別	
--4.EQ_SIZE			裝備尺寸	
--5.EQ_BRAND		裝備品牌	
--6.EQ_PRICE		裝備價格	
--7.EQ_STATUS		裝備狀態	
--8.EQ_PIC			裝備圖片	
--9.EQ_DETAIL		裝備敘述	
--10.TYPE_EQ_NUM	裝備種類總數編號	

INSERT INTO EQUIPMENT(EQ_NUM,EQ_NAME,EQ_TYPE,EQ_SIZE,EQ_BRAND,EQ_PRICE,EQ_STATUS,TYPE_EQ_NUM)
VALUES ('EQ'||LPAD(to_char(SEQ_EQ.nextval), 8, '0'),'超輕一人帳篷','帳篷','1人','Hilleberg',700,1,'ET00000001');

INSERT INTO EQUIPMENT(EQ_NUM,EQ_NAME,EQ_TYPE,EQ_SIZE,EQ_BRAND,EQ_PRICE,EQ_STATUS,TYPE_EQ_NUM)
VALUES ('EQ'||LPAD(to_char(SEQ_EQ.nextval), 8, '0'),'背包型4人帳篷','帳篷','4人','Hilleberg',500,1,'ET00000002');

INSERT INTO EQUIPMENT(EQ_NUM,EQ_NAME,EQ_TYPE,EQ_SIZE,EQ_BRAND,EQ_PRICE,EQ_STATUS,TYPE_EQ_NUM)
VALUES ('EQ'||LPAD(to_char(SEQ_EQ.nextval), 8, '0'),'T字鋁合金避震登山杖','登山杖','100CM','Komperdell',250,1,'ET00000003');

INSERT INTO EQUIPMENT(EQ_NUM,EQ_NAME,EQ_TYPE,EQ_SIZE,EQ_BRAND,EQ_PRICE,EQ_STATUS,TYPE_EQ_NUM)
VALUES ('EQ'||LPAD(to_char(SEQ_EQ.nextval), 8, '0'),'鋁合金橡膠握把登山杖','登山杖','100CM','Komperdell',200,1,'ET00000004');

INSERT INTO EQUIPMENT(EQ_NUM,EQ_NAME,EQ_TYPE,EQ_SIZE,EQ_BRAND,EQ_PRICE,EQ_STATUS,TYPE_EQ_NUM)
VALUES ('EQ'||LPAD(to_char(SEQ_EQ.nextval), 8, '0'),'H3.2伸縮調焦頭燈','照明燈','120流明','LED LENSER',120,1,'ET00000005');

INSERT INTO EQUIPMENT(EQ_NUM,EQ_NAME,EQ_TYPE,EQ_SIZE,EQ_BRAND,EQ_PRICE,EQ_STATUS,TYPE_EQ_NUM)
VALUES ('EQ'||LPAD(to_char(SEQ_EQ.nextval), 8, '0'),'充電式伸縮調焦手電筒','照明燈','850流明','LED LENSER',300,1,'ET00000006');

INSERT INTO EQUIPMENT(EQ_NUM,EQ_NAME,EQ_TYPE,EQ_SIZE,EQ_BRAND,EQ_PRICE,EQ_STATUS,TYPE_EQ_NUM)
VALUES ('EQ'||LPAD(to_char(SEQ_EQ.nextval), 8, '0'),'多功能強光頭燈組','照明燈','2000流明','LED LENSER',320,1,'ET00000007');

INSERT INTO EQUIPMENT(EQ_NUM,EQ_NAME,EQ_TYPE,EQ_SIZE,EQ_BRAND,EQ_PRICE,EQ_STATUS,TYPE_EQ_NUM)
VALUES ('EQ'||LPAD(to_char(SEQ_EQ.nextval), 8, '0'),'雪地攀登鍛造技術冰斧','冰斧','53,58,66CM','Komperdell',300,1,'ET00000008');

INSERT INTO EQUIPMENT(EQ_NUM,EQ_NAME,EQ_TYPE,EQ_SIZE,EQ_BRAND,EQ_PRICE,EQ_STATUS,TYPE_EQ_NUM)
VALUES ('EQ'||LPAD(to_char(SEQ_EQ.nextval), 8, '0'),'安全頭盔','安全帽','53-61CM','Mammut',150,1,'ET00000009');

INSERT INTO EQUIPMENT(EQ_NUM,EQ_NAME,EQ_TYPE,EQ_SIZE,EQ_BRAND,EQ_PRICE,EQ_STATUS,TYPE_EQ_NUM)
VALUES ('EQ'||LPAD(to_char(SEQ_EQ.nextval), 8, '0'),'靜力繩','繩線','11mm','Beal',200,1,'ET00000010');

INSERT INTO EQUIPMENT(EQ_NUM,EQ_NAME,EQ_TYPE,EQ_SIZE,EQ_BRAND,EQ_PRICE,EQ_STATUS,TYPE_EQ_NUM)
VALUES ('EQ'||LPAD(to_char(SEQ_EQ.nextval), 8, '0'),'基本款防墜落安全吊帶','吊帶','1人','Petzl',200,1,'ET00000011');

INSERT INTO EQUIPMENT(EQ_NUM,EQ_NAME,EQ_TYPE,EQ_SIZE,EQ_BRAND,EQ_PRICE,EQ_STATUS,TYPE_EQ_NUM)
VALUES ('EQ'||LPAD(to_char(SEQ_EQ.nextval), 8, '0'),'半固定式冰爪','冰爪','10爪','Komperdell',150,1,'ET00000012');










